CREATE TABLE IF NOT EXISTS plays (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    hash      TEXT    NOT NULL REFERENCES tracks(hash) ON DELETE CASCADE,
    played_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS skips (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    hash       TEXT    NOT NULL REFERENCES tracks(hash) ON DELETE CASCADE,
    skipped_at INTEGER NOT NULL
);
